"""initial

Revision ID: d8f775aa831e
Revises: 
Create Date: 2025-04-16 17:31:28.001630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f775aa831e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pvztable',
    sa.Column('registrationDate', sa.DateTime(), nullable=False),
    sa.Column('city', sa.Enum('moscow', 'spb', 'kazan', name='city_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pvztable_id'), 'pvztable', ['id'], unique=False)
    op.create_table('user',
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('employee', 'moderator', name='role_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('reception',
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('pvzId', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'close', name='reception_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pvzId'], ['pvztable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reception_id'), 'reception', ['id'], unique=False)
    op.create_table('product',
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('electonic', 'clothes', 'shoes', name='product_type_enum'), nullable=False),
    sa.Column('receptionId', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['receptionId'], ['reception.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_reception_id'), table_name='reception')
    op.drop_table('reception')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_pvztable_id'), table_name='pvztable')
    op.drop_table('pvztable')
    # ### end Alembic commands ###
